In [10]:
import numpy as np
print(np.__version__)

1.19.1


In [27]:
a =np.arange(15).reshape(3,5)
print(a)
a.ndim
a.dtype.name
a.itemsize
a.size
a.data
#TODO
'''
Refactor all the code
Add Commentes 
'''

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
