# Numpy
--- 
Provides An array object of arbitrary homogeneous items Fast mathematical operations over arrays Linear Algebra, Fourier Transforms Random Number Generation

In [5]:
import numpy as np
print(np.__version__)

1.18.1


In [4]:
a =np.arange(15).reshape(3,5)
'''Prints the array '''
print(a)
#number of array dimensions
print(a.ndim)
#get array data-descriptor
print(a.dtype.name)
#length of one element in bytes
print(a.itemsize)
#number of elements in the gentype
print(a.size)
#pointer to start of data
print(a.data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
int32
4
15


test
