# Numpy
--- 
NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

In [1]:
import numpy as np
np.__version__ 

'1.18.1'

In [ ]:
#    we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.
a = np.array([1,2,3])
a

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [1]:
# Accessing the elemntes 
# array_name[index]
a[0]

NameError: name 'a' is not defined

In [2]:
a = np.zeros(2)
a

array([0., 0.])

In [6]:
a= np.ones(2)
a

array([1., 1.])

In [20]:
a = np.empty(1)
a

array([1.69121367e-306])